use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64};
use rand::RngCore;
use serde::Serialize;

use super::{aes_ecb_decrypt, aes_ecb_encrypt, load_rsa, rsa_oaep_decrypt, rsa_oaep_encrypt};
use crate::{Error, Result};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EncryptedRequest {
    /// Base64 of the AES-128-ECB/PKCS#7 encrypted JSON body.
    pub body: String,
    /// Base64 of RSA-OAEP(SHA1)(base64(raw AES key)).
    pub encrypted_key: String,
}

/// Encrypt a JSON payload into `(body_b64, encrypted_key_b64)`.
pub fn encrypt_request<T: Serialize>(payload: &T) -> Result<(String, String)> {
    let encrypted = encrypt_request_envelope(payload)?;
    Ok((encrypted.body, encrypted.encrypted_key))
}

/// Structured form of [`encrypt_request`] for callers that prefer named fields.
pub fn encrypt_request_envelope<T: Serialize>(payload: &T) -> Result<EncryptedRequest> {
    let plaintext = serde_json::to_vec(payload)?;
    let mut aes_key = [0_u8; 16];
    rand::rng().fill_bytes(&mut aes_key);
    let body = aes_ecb_encrypt(&plaintext, &aes_key)?;
    let wrapped_key = rsa_oaep_encrypt(&load_rsa()?.0, BASE64.encode(aes_key).as_bytes())?;
    Ok(EncryptedRequest {
        body: BASE64.encode(body),
        encrypted_key: BASE64.encode(wrapped_key),
    })
}

/// Decrypt a response envelope and require UTF-8 plaintext.
pub fn decrypt_response(body_b64: &str, encrypted_key_b64: &str) -> Result<String> {
    Ok(String::from_utf8(decrypt_response_bytes(
        body_b64,
        encrypted_key_b64,
    )?)?)
}

/// Binary form of [`decrypt_response`] for callers that deserialize from bytes.
pub fn decrypt_response_bytes(body_b64: &str, encrypted_key_b64: &str) -> Result<Vec<u8>> {
    let (_, private) = load_rsa()?;
    let wrapped_key = BASE64.decode(encrypted_key_b64.trim())?;
    let encoded_key = rsa_oaep_decrypt(&private, &wrapped_key)?;
    let encoded_key = std::str::from_utf8(&encoded_key)
        .map_err(|error| Error::Crypto(format!("decoded AES key is not UTF-8: {error}")))?;
    let aes_key = BASE64.decode(encoded_key)?;
    let body = BASE64.decode(body_b64.trim())?;
    aes_ecb_decrypt(&body, &aes_key)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rsa::traits::PublicKeyParts;
    use serde_json::json;

    #[test]
    fn encrypted_body_does_not_contain_token_plaintext() {
        let token = "access-token-that-must-not-leak";
        let envelope =
            encrypt_request_envelope(&json!({"token": token, "prompt": "hello"})).unwrap();
        assert!(!envelope.body.contains(token));
        assert_eq!(BASE64.decode(&envelope.body).unwrap().len() % 16, 0);
        assert_eq!(BASE64.decode(&envelope.encrypted_key).unwrap().len(), 256);
    }

    #[test]
    fn response_decryption_roundtrip_uses_bundled_private_key() {
        let (_, private) = load_rsa().unwrap();
        let public = rsa::RsaPublicKey::from(&private);
        assert_eq!(private.n().bits(), 2048);
        let key = [0x42_u8; 16];
        let plaintext = serde_json::to_vec(&json!({"message": "你好"})).unwrap();
        let body = aes_ecb_encrypt(&plaintext, &key).unwrap();
        let wrapped = rsa_oaep_encrypt(&public, BASE64.encode(key).as_bytes()).unwrap();
        assert_eq!(
            decrypt_response_bytes(&BASE64.encode(body), &BASE64.encode(wrapped)).unwrap(),
            plaintext
        );
    }

    #[test]
    fn response_decryption_matches_python_fixture() {
        // Generated by Python `cryptography` using OAEP(MGF1(SHA1), SHA1)
        // and AES-128-ECB/PKCS7 against the embedded response key.
        const BODY: &str = "eWhStNg1Mu5d+2DPCwW4lZmL6q3nn9MUpPPVnCLyt5WWY+5DUIcX4acsuqsgvMaRtJhA6f1DyF4tFqDrakv+Bw==";
        const ENCRYPTED_KEY: &str = "Nm7RVhkX9EAwuow4Z4TZw99LsXDn0DONE5nqCDwIqiytfNCGSVCfqqc/n+xPEvFDL5SYX/9TEhon3m0Z0fDFmGueTmJ4KtjwRlf/Pmo0MXIZaMIY2Q0IybtE4o18gkl+0kf1tonSwq7HcK4w3KdJWsbdMeSDBif4WOSNruVuIUEkfKqZkFyT5voONEGciJbKPNiaEVM9+bAicIZKCy6Y75mMeQV0Ieudt5GHmER3esaYThM9wD3JBenIQBp8sym53g6IroZ7ActSANbv9C+H5BYn2v8qAqqX2FMmHkGw3cKFEREYNnc5jsaCbWmRTVqDIb07++2iIvewREOJU8tYzw==";
        let decrypted = decrypt_response(BODY, ENCRYPTED_KEY).unwrap();
        let value: serde_json::Value = serde_json::from_str(&decrypted).unwrap();
        assert_eq!(value["hello"], "world");
        assert_eq!(value["n"], 123);
        assert_eq!(value["中文"], "测试");
    }
}
