#!/usr/bin/env python3
"""Ledger of every test that a platform `cfg` keeps out of a build, and what that costs.

Why this exists rather than a comment in a review: `#[ignore]` has an inventory
(`scripts/ci/ignored-tests.py`, which refuses an ignored test without a reason), but a test
behind `#[cfg(unix)]` had none, and it is skipped just as completely -- more so, because it is not
even compiled, so no runner reports it as skipped. On 2026-10-03 the first full Windows leg made
that concrete: a family of persistent-shell assertions went red on `windows-latest`, and the pass
that turned the leg green did it by putting `#[cfg(unix)]` on eleven of them. The suite went green
without any behaviour being fixed, and nothing in the repository could afterwards say which tests
had been gated for that reason or what stopped being executed there.

This script produces the inventory and refuses five kinds of drift:

  * a gated test with no ledger row (new gating, needs a reason before it can merge);
  * a ledger row whose site is gone, or whose platform set, non-platform `cfg`, or marker set
    changed (the row was edited out from under the test, or the test was rewritten under it);
  * a row without a real reason, or one still carrying the import marker once the unreviewed
    budget (`--max-unreviewed`) is spent;
  * more platform-blind files than `--max-blind-windows` / `--max-blind-macos` allow;
  * more gated tests with no platform assumption in them than `--max-assumption-free` allows, with
    the offending tests named on stderr (`--list-assumption-free` prints the list on its own).

A file is blind for a platform if it contains at least one platform-gated test and no test at all
that would run on that platform -- so `#[cfg(unix)]` tests in a file with no Windows-capable test
leave that file executing nothing on Windows, and the two caps hold that count down. All four
numbers are checked, not merely printed, so they can only move down.

The platform set of a test is the intersection of every `cfg` that applies to it, not just the
attribute on the `fn`: a `#[cfg(unix)] mod tests { ... }` gates everything inside it, and a file
starting `#![cfg(unix)]` gates the whole file. Non-platform `cfg` (features) does not narrow the
platform set but is recorded in its own column, because a test gated on both is hidden behind two
independent switches.

The `assumptions` column answers the question the debt note asked: which gated tests are not about
the platform they are gated to. It lists the POSIX (or Windows) things visible inside the test body
and in the name of the file holding it, and `none` means none were found, which makes the row worth
naming. A row is identified by that column too, so the ledger cannot keep an old claim after a test
gains or loses a marker. The line number is the one column that is not part of a row's identity: it
is a navigation hint regenerated by `--write-baseline`, because otherwise every edit made above a
gated test would demand a rewrite whose diff says nothing.

Stated limits, because each one is a way for new gating to look ordinary:

  * `cfg` expressions are read as written on the item. `cfg_attr(...)` is understood only in the
    `cfg_attr(<platform>, ignore = "...")` shape, counted as a test that exists on that platform
    and does not run there; any other `cfg_attr` is invisible here.
  * `cfg` applied by a macro (`include!`, a custom test-attribute macro) is invisible.
  * a file pulled in by a platform-gated `mod` declaration does not inherit that gate here, so a
    file compiled only on unix reads as ungated. The scan covers every `.rs` file in the
    repository except `target/`, `.git/`, `node_modules/`, `dist/` and `test-results/`; members
    outside `crates/` are scanned, so nothing cargo builds is graded by a narrower walk.
  * `cfg(not(unix))` counts as covering `other` as well as `windows`, because that is what it
    covers. Nothing here claims any runner executed anything: the ledger records what the source
    excludes, which is not the same fact and is not a substitute for the platform legs.
  * a `none` in `assumptions` is a claim about the test's own text. It is wrong in two known ways:
    the assumption may sit inside a helper the test calls (calls are not followed), or inside the
    production code under test. Markers are therefore broad and portable spellings are left out;
    `none` says a test is worth a look, not that it would pass elsewhere.

    scripts/ci/platform-gated-tests.py                       # the summary
    scripts/ci/platform-gated-tests.py --table               # every ledger row
    scripts/ci/platform-gated-tests.py --list-assumption-free  # gates with nothing to gate
    scripts/ci/platform-gated-tests.py --write-baseline scripts/ci/platform-gated-tests.tsv
    scripts/ci/platform-gated-tests.py --check-baseline scripts/ci/platform-gated-tests.tsv \
        --max-unreviewed N --max-blind-windows N --max-blind-macos N --max-assumption-free N
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import Counter
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[2]
MIN_REASON = 20
UNREVIEWED = "inherited 2026-10-03 (pre-existing gating, not reviewed row by row)"
PLATFORMS = ("linux", "macos", "other-unix", "windows", "other")
ALL_PLATFORMS = frozenset(PLATFORMS)
UNIXISH = frozenset({"linux", "macos", "other-unix"})
HEADER = ("kind", "crate", "file", "line", "function", "runs_on", "extra_cfg", "assumptions",
          "reason")
KIND_GATE = "cfg-gate"
KIND_IGNORE = "cfg-attr-ignore"
KIND_GATE_IGNORED = "cfg-gate-and-ignore"

# An attribute path may be `test`, `tokio::test`, `test_log::test`, `serial::test`.
TEST_ATTR = re.compile(r"(?:^|::)test$")
OTHER_TEST_ATTR = frozenset({"rstest", "quickcheck", "proptest"})
ATTR_HEAD = re.compile(r"^([A-Za-z_][A-Za-z0-9_:!]*)\s*(?:\((.*)\))?$", re.DOTALL)
COMBINATOR = re.compile(r"^(all|any|not)\s*\((.*)\)$", re.DOTALL)
ATOM = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*(?:=\s*\"([^\"]*)\")?$")
FN_NAME = re.compile(r"(?:^|[\s>])fn\s+([A-Za-z0-9_]+)")
INNER_CFG = re.compile(r"^[ \t]*#!\[cfg\((.*)\)\][ \t]*$", re.MULTILINE)
SKIP_DIRS = frozenset({"target", ".git", "node_modules", "dist", "test-results"})
RAW_STRING = re.compile(r'r(#*)"')
CHAR_LITERAL = re.compile(r"'(?:\\.|[^\\'])'")
# The only places `blank_noise` can change a character: a comment opener, a string opener, or a
# character literal. Every other byte is copied, so the blanker searches for these instead of
# inspecting each character.
NOISE = re.compile(r"/[/*]|r#*\"|['\"]")
# A file without any of these words cannot contain a platform gate, so this is a fast prefilter
# and not a filter on the answer: every platform atom's spelling is in it.
PLATFORM_WORD = re.compile(r"unix|windows|macos|linux|darwin|target_os|target_family|bsd|dragonfly|ios")
TARGET_OS = {
    "linux": {"linux"},
    "macos": {"macos"},
    "ios": {"macos"},
    "tvos": {"macos"},
    "watchos": {"macos"},
    "windows": {"windows"},
    "android": {"other"},
    "dragonfly": {"other-unix"},
    "freebsd": {"other-unix"},
    "netbsd": {"other-unix"},
    "openbsd": {"other-unix"},
    "illumos": {"other-unix"},
    "solaris": {"other-unix"},
    "redox": {"other"},
    "haiku": {"other"},
    "vxworks": {"other"},
    "nuttx": {"other"},
    "emscripten": {"other"},
    "uefi": {"other"},
    "hermit": {"other"},
    "none": {"other"},
}

# What a test has to mention for a platform gate on it to be about that platform rather than about
# convenience. These decide the ledger's `assumptions` column: `none` is the list the debt note
# asked to be named -- gating whose test shows nothing the other side could not run.
#
# The lists are deliberately broad, because the two errors are not equally bad. A marker firing on a
# test that is in fact portable only leaves that row unnamed here; a missing marker would make the
# gate demand cross-platform work from a test that genuinely cannot run there. Portable spellings
# are therefore left out even when they look platform-flavoured (`child.kill()` and `Child::
# start_kill` work on Windows, so they are not evidence). Two known ways for `none` to be wrong: an
# assumption that lives inside a helper the test calls (helpers are not followed), and an assumption
# carried by the production code under test. That is why `none` is a budget the repository is held
# down to and reviewed by hand, not a claim that the test would pass on the other platform.
POSIX_ASSUMPTION: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (name, re.compile(pattern))
    for name, pattern in (
        ("std-os-unix", r"std::os::(unix|linux|macos)\b"),
        ("raw-fd", r"\b(RawFd|AsRawFd|AsFd|AsRawSocket|FromRawFd|BorrowedFd|OwnedFd)\b"),
        ("unix-ext-trait", r"\b(PermissionsExt|MetadataExt|ExitStatusExt|TerminalExt|RawMode)\b"),
        ("unix-socket", r"\b(UnixStream|UnixListener|UnixDatagram|vsock)|\.sock\b"),
        ("signal", r"\b(sigaction|killpg|waitpid|setsid|prctl)\b|SIG[A-Z]{2,6}|signal::(unix|nix)"),
        ("fork-daemon", r"\b(fork|posix_spawn|daemonize|reaper)\b"),
        ("file-mode", r"\b(chmod|chown|umask|S_[IRWXA-Z]{1,4})\b|0o[0-7]{3,4}|\.mode\(\s*0o"),
        ("symlink", r"\b(symlink|symlink_file|symlink_dir|hard_link|read_link)\b"),
        ("tty", r"\b(openpty|forkpty|termios|TcFlag|tcgetattr|ioctl|isatty|stty)\b"),
        ("uid-gid", r"\b(getuid|geteuid|getgid|setuid|setgid)\b|\b(Uid|Gid)::"),
        ("posix-path", r"/(tmp|usr|bin|etc|proc|dev|var|opt|home|sys|run|lib|sbin|Applications)/"
                       r"""|\$\{?HOME\}?|~/|\bHOME\.join\(|env\("HOME"\)"""),
        ("fs-root", r"""Path::new\(\s*\"/\"|PathBuf::from\(\s*\"/\"|join\(\"/\"\)"""),
        ("shell", r"\b(sh|bash|zsh|fish)\s+-c\b|/bin/(sh|bash)|\b(command -v|type -a|ulimit)\b"),
        ("posix-crate", r"\b(libc|nix|rustix)\s::"),
        ("mount-lock", r"\b(mount|unmount|umount|flock|statvfs|statfs|pivot_root|MemAvailable)\b"),
        ("unix-env", r"\bXDG_[A-Z_]+\b|\bLD_LIBRARY_PATH\b|\bgetpwuid\b"
                     r"|\b(DISPLAY|WAYLAND_DISPLAY|XAUTHORITY|SSH_AUTH_SOCK)\b"),
        ("x11-wayland", r"\b(xclip|xsel|wl-copy|wl-paste|wl-clipboard|x11|wayland|xcb|scrot)\b"),
        ("mac-service", r"\b(pbcopy|pbpaste|caffeinate|pmset|launchctl|launchd)\b"),
        ("systemd-dbus", r"\b(systemd|systemctl|dbus-send|sd_bus|journalctl|notify-send)\b"),
        ("unix-tool", r"\b(nproc|sysctl|getconf|pgrep|pkill|tmux|free -m)\b"),
        ("errno", r"from_raw_os_error"),
        ("nested-cfg-unix", r"""#!?\[cfg\(.*\b(unix|target_os\s*=\s*\"(linux|macos)\")"""),
    )
)
WINDOWS_ASSUMPTION: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (name, re.compile(pattern))
    for name, pattern in (
        ("std-os-windows", r"std::os::windows\b"),
        ("winapi", r"\b(windows|winapi|windows_sys|windows_targets|winreg)::"),
        ("win-call", r"\b(CreateProcess\w*|OpenProcess|TerminateProcess|WaitForSingleObject"
                     r"|CreateJobObject\w*|AssignProcessToJobObject|ShellExecute\w*"
                     r"|CREATE_NO_WINDOW|CREATE_NEW_CONSOLE|DeviceIoControl)\b"),
        ("drive-path", r"[A-Za-z]:\\{1,2}"),
        ("unc-path", r"\\\\[A-Za-z0-9_.-]+\\"),
        ("exe-suffix", r"\.exe\b|\bstd::env::consts::EXE_SUFFIX\b"),
        ("registry", r"\bHKEY_[A-Z_]+\b|\bRegistryKey\b"),
        ("windows-shell", r"\b(powershell|pwsh|cmd\.exe|cmd\s+/c|taskkill|conhost)\b"),
        ("errno", r"from_raw_os_error"),
        ("nested-cfg-windows", r"#!?\[cfg\(.*\bwindows\b"),
    )
)

# The same idea at file granularity: a file whose name is a POSIX noun (`flock_wait_tests.rs`,
# `pty.rs`) is about that platform even where an individual test inside it reads as portable, so
# naming such a test as a candidate would be wrong.
POSIX_PATH_WORDS = frozenset(
    "unix posix flock pty termios ioctl signal sigaction x11 wayland wl dbus systemd umask chmod "
    "chown symlink libc rustix nix darwin macos linux procfs sysfs mount setuid uid gid sudo "
    "ulimit rlimit fifo tty shm xdg clipboard xclip xsel pbcopy caffeinate socket pipe daemon"
    .split()
)
WINDOWS_PATH_WORDS = frozenset(
    "windows win win32 winapi registry powershell ntdll jobobject taskkill conhost wine drive"
    .split()
)


def path_words(rel: str) -> frozenset[str]:
    return frozenset(w for w in re.split(r"[^a-z0-9]+", rel.lower()) if w)


def assumption_label(body: str, runs_on: frozenset[str], words: frozenset[str]) -> str:
    """The platform assumptions visible in one test body and in the name of the file holding it.

    Only the families the test's own gating keeps out are considered: a unix-only test is asked
    what POSIX thing it needs, a Windows-only test what Windows thing it needs. `none` means
    neither family appeared, which is what makes the row worth naming.
    """
    missing = ALL_PLATFORMS - runs_on
    labels: list[str] = []
    if missing & {"windows", "other"}:
        labels += [name for name, rx in POSIX_ASSUMPTION if rx.search(body)]
        if words & POSIX_PATH_WORDS:
            labels.append("file-name")
    if missing & {"linux", "macos", "other-unix"}:
        labels += [name for name, rx in WINDOWS_ASSUMPTION if rx.search(body)]
        if words & WINDOWS_PATH_WORDS:
            labels.append("file-name")
    return ";".join(sorted(set(labels))) or "none"


def blank_noise(text: str, keep_strings: bool = False) -> str:
    """Blank comments and string literals, keeping every character position.

    Line numbers in the ledger have to be the ones an editor takes you to, so nothing here shifts
    offsets. Positions are what the caller uses: attribute *content* is sliced out of the raw text
    at the offsets found here, because blanking erases the `"macos"` in `cfg(target_os = "macos")`
    while leaving the attribute's position alone. A `#[cfg(unix)]` written in a comment or a string
    literal has no live `#` in the blanked copy, so it is not a gate.

    `keep_strings=True` leaves string contents alone while still blanking comments, which is what
    the platform-assumption markers want: `Command::new("chmod")` and `"/tmp/x"` are assumptions,
    and a `chmod` mentioned only in a doc comment is not.
    """
    out = list(text)
    i = 0
    n = len(text)
    depth = 0
    while i < n:
        if depth:
            if text.startswith("*/", i):
                depth -= 1
                out[i] = out[i + 1] = " "
                i += 2
                continue
            if text[i] != "\n":
                out[i] = " "
            i += 1
            continue
        # Everything between two interesting characters is copied through untouched, so the scan
        # jumps to the next one instead of stepping over it. Without this the pass is a per-character
        # Python loop over every line of Rust in the repository, and the gate stops being runnable.
        jump = NOISE.search(text, i)
        if jump is None:
            break
        i = jump.start()
        if text.startswith("/*", i):
            depth += 1
            out[i] = out[i + 1] = " "
            i += 2
            continue
        if text.startswith("//", i):
            while i < n and text[i] != "\n":
                out[i] = " "
                i += 1
            continue
        raw = RAW_STRING.match(text, i)
        if raw:
            terminator = '"' + "#" * len(raw.group(1))
            start = raw.end()
            end = text.find(terminator, start)
            stop = n if end < 0 else end + len(terminator)
            if not keep_strings:
                for k in range(i, min(stop, n)):
                    if text[k] != "\n":
                        out[k] = " "
            i = max(stop, i + 1)
            continue
        if text[i] == '"':
            j = i + 1
            while j < n and text[j] not in "\n\"":
                j += 2 if text[j] == "\\" else 1
            if not keep_strings:
                for k in range(i, min(j + 1, n)):
                    if text[k] != "\n":
                        out[k] = " "
            i = max(j + 1, i + 1)
            continue
        if text[i] == "'":
            literal = CHAR_LITERAL.match(text, i)
            if literal:
                for k in range(i, literal.end()):
                    out[k] = " "
                i = literal.end()
                continue
        i += 1
    return "".join(out)


def split_top(expr: str) -> list[str]:
    """Split a comma-separated cfg argument list at depth one."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in expr:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(current))
            current = []
            continue
        current.append(ch)
    if "".join(current).strip():
        parts.append("".join(current))
    return parts


def atom_platforms(name: str, value: str | None) -> frozenset[str] | None:
    """Platforms an `ident` / `ident = "value"` cfg selects, or None if it is not about platforms.

    None means "this says nothing about the platform": it must not narrow anything, and the caller
    records it in `extra_cfg`. An unrecognised `target_os` value returns None on purpose, so a
    spelling this file does not know shows up in the `extra_cfg` column for a human to read rather
    than silently selecting nothing.
    """
    if name == "unix":
        return UNIXISH
    if name == "windows":
        return frozenset({"windows"})
    if name == "target_os" and value is not None:
        if value not in TARGET_OS:
            return None
        return frozenset(TARGET_OS[value])
    if name == "target_family" and value is not None:
        if value == "unix":
            return UNIXISH
        if value == "windows":
            return frozenset({"windows"})
    return None


def eval_cfg(expr: str) -> tuple[frozenset[str], list[str]]:
    """Evaluate a cfg expression into (platforms it selects, terms that are not platforms)."""
    platforms = ALL_PLATFORMS
    extra: list[str] = []
    for part in split_top(expr):
        part = part.strip()
        if not part:
            continue
        combinator = COMBINATOR.match(part)
        if combinator:
            kind, inner = combinator.group(1), combinator.group(2)
            if kind == "not":
                sub, sub_extra = eval_cfg(inner)
                platforms &= ALL_PLATFORMS - sub
                extra += sub_extra
                continue
            if kind == "all":
                # `all(a, b)` intersects, and eval_cfg already treats a comma as AND.
                sub, sub_extra = eval_cfg(inner)
                platforms &= sub
                extra += sub_extra
                continue
            union = frozenset()
            for branch in split_top(inner):
                sub, sub_extra = eval_cfg(branch)
                union |= sub
                extra += sub_extra
            platforms &= union
            continue
        atom = ATOM.match(part)
        if not atom:
            extra.append(" ".join(part.split()))
            continue
        resolved = atom_platforms(atom.group(1), atom.group(2))
        if resolved is None:
            extra.append(" ".join(part.split()))
            continue
        platforms &= resolved
    return platforms, extra


def brace_end(clean: str, open_brace: int) -> int:
    depth = 0
    for i in range(open_brace, len(clean)):
        if clean[i] == "{":
            depth += 1
        elif clean[i] == "}":
            depth -= 1
            if depth == 0:
                return i + 1
    return len(clean)


def attribute_blocks(clean: str, raw: str) -> list[dict]:
    """Every run of `#[...]` attributes, with its offsets, names and cfg conditions.

    A run is one or more consecutive attributes; the item after the run is what they apply to.
    `cfg_attr(<plat>, ignore = "...")` is told apart from a plain `#[ignore]`: the first makes a
    test that exists on that platform and is skipped there, the second skips it everywhere and is
    already inventoried by `ignored-tests.py`.
    """
    blocks: list[dict] = []
    n = len(clean)
    i = 0
    while i < n:
        if clean[i] != "#" or not clean.startswith("#[", i):
            i += 1
            continue
        start = i
        names: list[str] = []
        cfgs: list[str] = []
        ignore_if: list[str] = []
        plain_ignore = False
        j = i
        while j < n and clean.startswith("#[", j):
            depth = 0
            k = j
            while k < n:
                ch = clean[k]
                if ch in "[(":
                    depth += 1
                elif ch in "])":
                    depth -= 1
                    if depth == 0:
                        break
                k += 1
            # The offsets come from the blanked text, so an attribute written inside a comment
            # or a string literal is never matched. The content comes from the raw text, because
            # blanking erases the `"macos"` in `cfg(target_os = "macos")` -- positions are
            # preserved between the two, so the slice is the same attribute either way.
            head = ATTR_HEAD.match(raw[j + 2 : k])
            if head:
                name, arg = head.group(1), head.group(2) or ""
                names.append(name)
                if name == "cfg":
                    cfgs.append(arg)
                elif name == "ignore":
                    plain_ignore = True
                elif name == "cfg_attr":
                    pieces = split_top(arg)
                    if len(pieces) >= 2 and re.match(r"^\s*ignore\b", ",".join(pieces[1:])):
                        # The condition says where the test is SKIPPED, which is the complement of
                        # where it runs; keeping it out of `cfgs` is what stops the two from being
                        # read as the same kind of gate.
                        ignore_if.append(pieces[0])
            j = k + 1
            while j < n and clean[j] in " \t\r\n":
                j += 1
        blocks.append(
            {
                "start": start,
                "after": j,
                "names": names,
                "cfgs": cfgs,
                "ignore_if": ignore_if,
                "plain_ignore": plain_ignore,
            }
        )
        i = max(j, start + 1)
    return blocks


def gated_spans(clean: str, blocks) -> list[tuple[frozenset[str], int, int]]:
    """(platforms, from, to) for every cfg'd item, extending over its braces when it has a body.

    An item with a body gates everything inside the matching brace; an item without one (`use`,
    a `mod` declaration, a field) gates only up to its `;`. Without the second rule a
    `#[cfg(unix)] use foo::Bar;` line would appear to gate the rest of the file.
    """
    spans: list[tuple[frozenset[str], int, int]] = []
    for block in blocks:
        cfgs = block["cfgs"]
        if not cfgs:
            continue
        platforms = ALL_PLATFORMS
        for arg in cfgs:
            platforms &= eval_cfg(arg)[0]
        if platforms == ALL_PLATFORMS:
            continue
        after = block["after"]
        brace = clean.find("{", after)
        semi = clean.find(";", after)
        if brace >= 0 and (semi < 0 or brace < semi):
            end = brace_end(clean, brace)
        elif semi >= 0:
            end = semi + 1
        else:
            end = after
        spans.append((platforms, block["start"], end))
    return spans


def crate_of(rel: Path, crate_dirs: frozenset[tuple[str, ...]]) -> str:
    """The package the file belongs to: the nearest ancestor holding a `Cargo.toml`.

    Deriving it from a directory layout instead would read `crates/foo/src/lib.rs` as crate `src`
    the first time the repository grows a one-level member, and the crate column is what the
    summary groups by.
    """
    parts = rel.parts
    for depth in range(len(parts) - 1, 0, -1):
        if parts[:depth] in crate_dirs:
            return parts[depth - 1]
    return parts[0] if parts else "."


def scan_file(raw: str, rel: Path, crate_dirs: frozenset[tuple[str, ...]]) -> list[dict]:
    clean = blank_noise(raw)
    # Same offsets, but string literals survive: the assumption markers have to see
    # `Command::new("chmod")`, and a `chmod` mentioned only in a comment must not count. Built on
    # first need, because most scanned files contain no gated test and the second text pass is not
    # free across a repository this size.
    strings: str | None = None
    blocks = attribute_blocks(clean, raw)
    spans = gated_spans(clean, blocks)
    file_platforms = ALL_PLATFORMS
    file_extra: list[str] = []
    for m in INNER_CFG.finditer(raw):
        # A `#![cfg(...)]` written in a comment is blanked in `clean`, so the same offset holding
        # a `#` there is what makes this match a real inner attribute.
        if clean[m.start()] != "#":
            continue
        platforms, extra = eval_cfg(m.group(1))
        file_platforms &= platforms
        file_extra += extra
    rows: list[dict] = []
    for block in blocks:
        names = block["names"]
        if not (
            any(TEST_ATTR.search(name) for name in names)
            or any(name in OTHER_TEST_ATTR for name in names)
        ):
            continue
        after = block["after"]
        found = FN_NAME.search(clean[after : after + 400])
        if not found:
            continue
        own = ALL_PLATFORMS
        extra = list(file_extra)
        for arg in block["cfgs"]:
            platforms, terms = eval_cfg(arg)
            own &= platforms
            extra += terms
        for span_platforms, span_start, span_end in spans:
            if span_start <= block["start"] < span_end:
                own &= span_platforms
        platforms = file_platforms & own
        if block["ignore_if"]:
            kind = KIND_IGNORE
            for cond in block["ignore_if"]:
                cond_platforms, cond_extra = eval_cfg(cond)
                platforms -= cond_platforms
                extra += cond_extra
        elif platforms != ALL_PLATFORMS and block["plain_ignore"]:
            kind = KIND_GATE_IGNORED
        else:
            kind = KIND_GATE
        assumptions = "-"
        if platforms != ALL_PLATFORMS:
            # Brace counting uses the fully blanked copy, so a `{` inside a string literal cannot
            # open a phantom block; the text is then sliced from the copy that kept strings.
            brace = clean.find("{", after + found.end())
            if 0 <= brace < len(clean) and clean[brace] == "{":
                if strings is None:
                    strings = blank_noise(raw, keep_strings=True)
                end = brace_end(clean, brace)
                assumptions = assumption_label(
                    strings[brace : end + 1], platforms, path_words(rel.as_posix())
                )
        rows.append(
            {
                "kind": kind,
                "crate": crate_of(rel, crate_dirs),
                "file": rel.as_posix(),
                "line": clean.count("\n", 0, block["start"]) + 1,
                "function": found.group(1),
                "runs_on": platforms,
                "extra_cfg": sorted(set(extra)),
                "assumptions": assumptions,
            }
        )
    return rows


def scan(root: Path) -> list[dict]:
    """Every test function in the repository with the platform set it would run on.

    The walk prunes `SKIP_DIRS` on the way down instead of filtering after the fact: this
    repository's `target/` holds hundreds of gigabytes, and a `rglob` that walked it before
    discarding the hits made the gate take minutes on a warm checkout.
    """
    rows: list[dict] = []
    # Two passes: the crate column is the nearest ancestor with a Cargo.toml, and a file may sit
    # in the tree before the directory that declares the package is walked.
    found: list[tuple[Path, Path]] = []
    crate_dirs: set[tuple[str, ...]] = set()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        if "Cargo.toml" in filenames:
            crate_dirs.add(Path(dirpath).relative_to(root).parts)
        for name in sorted(filenames):
            if name.endswith(".rs"):
                path = Path(dirpath) / name
                found.append((path, path.relative_to(root)))
    crate_set = frozenset(crate_dirs)
    for path, rel in found:
        try:
            raw = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        # A file with no platform word anywhere cannot host a platform-gated test, and cannot
        # carry a `#![cfg(...)]` file gate either. Skipping those files is what keeps this a
        # gate that runs in seconds rather than a whole-repository text pass.
        if not PLATFORM_WORD.search(raw):
            continue
        rows += scan_file(raw, rel, crate_set)
    return rows


def ledger_rows(rows: list[dict]) -> list[dict]:
    """The rows that belong in the ledger: the ones some platform does not build."""
    return [r for r in rows if r["runs_on"] != ALL_PLATFORMS]


def runs_on_label(platforms: object) -> str:
    """The `runs_on` spelling, accepting either a scanned platform set or a ledger string."""
    if isinstance(platforms, str):
        return platforms.strip()
    return "+".join(p for p in PLATFORMS if p in platforms)


def extra_label(terms: object) -> str:
    """The non-platform part of a test's gating, in the spelling the ledger stores.

    It is part of a row's identity: tightening `cfg(all(unix, feature = "a"))` to another feature
    changes what the row documents even though the platform set is unchanged.
    """
    if isinstance(terms, str):
        return " ".join(terms.split()) or "-"
    return ";".join(" ".join(t.split()) for t in sorted(set(terms))) or "-"


def key_of(row: dict) -> tuple[str, str, str, str, str, str]:
    """What makes a ledger row the row for a test.

    The line number is deliberately absent: an edit anywhere above a gated test would otherwise
    demand a ledger rewrite that says nothing about the debt, so the line stays a navigation hint
    that `--write-baseline` regenerates and `--check-baseline` does not compare. Everything that
    says what is being hidden is present, including the body's platform assumptions.
    """
    return (
        row["file"],
        row["function"],
        runs_on_label(row["runs_on"]),
        row["kind"],
        extra_label(row["extra_cfg"]),
        row["assumptions"].strip() or "none",
    )


def describe_key(key: tuple[str, str, str, str, str, str]) -> str:
    file, function, runs_on, kind, extra, assumptions = key
    extra = "" if extra == "-" else f" extra_cfg={extra}"
    return (
        f"{file} {function} [{kind}] runs on {runs_on} only{extra} "
        f"assumptions={assumptions}"
    )


def blind_files(rows: list[dict]) -> dict[str, set[str]]:
    """Files with at least one gated test and no test at all that runs on the platform.

    Ungated tests run everywhere, so one ungated test in the file is enough to clear it; that is
    why the caller passes every test row, not just the ledger rows.
    """
    covered: dict[str, set[str]] = {}
    gated_files: set[str] = set()
    for r in rows:
        covered.setdefault(r["file"], set()).update(r["runs_on"])
        if r["runs_on"] != ALL_PLATFORMS:
            gated_files.add(r["file"])
    out = {"windows": set(), "macos": set(), "linux": set()}
    for path, platforms in covered.items():
        if path not in gated_files:
            continue
        for platform in out:
            if platform not in platforms:
                out[platform].add(path)
    return out


def assumption_free(rows: list[dict]) -> list[dict]:
    """Gated tests whose own body shows no assumption about the platform the gate keeps out.

    This is the list the debt note asked to be named: gating that is only a POSIX fixture in
    appearance, and that could be made to run on the other platform. `none` is a claim about the
    test's text, not proof, so the count is budgeted rather than trusted.
    """
    return [r for r in rows if r["kind"] != KIND_IGNORE and r["assumptions"] == "none"]


def render_table(rows: list[dict]) -> str:
    lines = ["\t".join(HEADER)]
    for r in sorted(rows, key=lambda r: (r["file"], r["line"])):
        lines.append(
            "\t".join(
                (
                    r["kind"],
                    r["crate"],
                    r["file"],
                    str(r["line"]),
                    r["function"],
                    runs_on_label(r["runs_on"]),
                    extra_label(r["extra_cfg"]),
                    r["assumptions"],
                    UNREVIEWED,
                )
            )
        )
    return "\n".join(lines)


def read_baseline(path: Path) -> list[dict]:
    rows = []
    header = "\t".join(HEADER)
    for lineno, line in enumerate(path.read_text(encoding="utf-8").split("\n"), 1):
        if not line.strip() or line.startswith("#") or line == header:
            continue
        cols = line.split("\t")
        if len(cols) != len(HEADER):
            raise SystemExit(f"{path}:{lineno}: expected {len(HEADER)} columns, got {len(cols)}")
        rows.append(dict(zip(HEADER, cols)))
    return rows


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    ap.add_argument("--table", action="store_true", help="print every ledger row")
    ap.add_argument("--write-baseline", type=Path)
    ap.add_argument("--check-baseline", type=Path)
    ap.add_argument("--max-unreviewed", type=int)
    ap.add_argument("--max-blind-windows", type=int)
    ap.add_argument("--max-blind-macos", type=int)
    ap.add_argument("--max-assumption-free", type=int,
                    help="budget for gated tests whose body shows no platform assumption")
    ap.add_argument("--list-assumption-free", action="store_true",
                    help="print every gated test whose body shows no platform assumption")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    root = args.root.resolve()
    rows = scan(root)
    ledger = ledger_rows(rows)
    gated = [r for r in ledger if r["kind"] != KIND_IGNORE]
    ignores = [r for r in ledger if r["kind"] == KIND_IGNORE]
    both = [r for r in ledger if r["kind"] == KIND_GATE_IGNORED]
    blind = blind_files(rows)
    free = assumption_free(ledger)

    if args.write_baseline:
        args.write_baseline.write_text(render_table(ledger) + "\n", encoding="utf-8")
        print(f"wrote {len(ledger)} rows to {args.write_baseline}")
        return 0

    problems: list[str] = []
    if args.check_baseline:
        # Multiset comparison, like scripts/ci/ignored-tests.py: the same test name can legitimately
        # appear twice in one file (two modules, identical gating), and a ledger must be able to say
        # so without the gate reading the second row as a duplicate.
        live = Counter(key_of(r) for r in ledger)
        first_live: dict[tuple[str, str, str, str, str, str], dict] = {}
        for r in ledger:
            first_live.setdefault(key_of(r), r)
        seen = Counter()
        for row in read_baseline(args.check_baseline):
            key = key_of(row)
            seen[key] += 1
            if live[key] == 0:
                # A rewritten cfg or a renamed test lands here. The row has to be re-derived, not
                # deleted: deleting it must never erase the debt the row describes.
                same = [describe_key(k) for k in live if k[0] == key[0] and k[1] == key[1]]
                hint = f"; the test is now {' / '.join(same)}" if same else "; the test is gone"
                problems.append(
                    f"stale baseline row {row['file']}:{row['line']} {row['function']}{hint}"
                )
            elif seen[key] > live[key]:
                problems.append(f"duplicate baseline row: {describe_key(key)}")
            reason = row["reason"].strip()
            if len(reason) < MIN_REASON:
                problems.append(
                    f"{row['file']}:{row['line']} {row['function']}: reason is {len(reason)} "
                    f"chars, needs >= {MIN_REASON}"
                )
        for key, row in first_live.items():
            if seen[key] < live[key]:
                problems.append(
                    f"unlisted platform-gated test {row['file']}:{row['line']} "
                    f"{row['function']} runs on {runs_on_label(row['runs_on'])} only"
                )
        unreviewed = sum(1 for row in read_baseline(args.check_baseline)
                         if row["reason"].strip() == UNREVIEWED)
        if args.max_unreviewed is not None and unreviewed > args.max_unreviewed:
            problems.append(
                f"{unreviewed} rows still carry the import marker, over the budget of "
                f"{args.max_unreviewed}"
            )
    if args.max_blind_windows is not None and len(blind["windows"]) > args.max_blind_windows:
        problems.append(
            f"{len(blind['windows'])} files have platform-gated tests and nothing that runs on "
            f"Windows, over the budget of {args.max_blind_windows}"
        )
    if args.max_blind_macos is not None and len(blind["macos"]) > args.max_blind_macos:
        problems.append(
            f"{len(blind['macos'])} files have platform-gated tests and nothing that runs on "
            f"macOS, over the budget of {args.max_blind_macos}"
        )
    if args.max_assumption_free is not None and len(free) > args.max_assumption_free:
        # Named here rather than only counted: the point of the number is the list, and a CI log
        # that says "613" tells nobody which gate to delete.
        problems.append(
            f"{len(free)} gated tests show no platform assumption in their body, over the budget "
            f"of {args.max_assumption_free}; these are candidates to un-gate: "
            + ", ".join(f"{r['file']}:{r['line']} {r['function']}" for r in free[:40])
        )

    if not args.quiet:
        by_crate: dict[str, int] = {}
        for r in gated:
            by_crate[r["crate"]] = by_crate.get(r["crate"], 0) + 1
        print(f"platform-gated tests: {len(gated)} in {len({r['file'] for r in gated})} files")
        print(f"platform-conditional #[ignore] (exists there, skipped there): {len(ignores)}")
        print(f"gated and also #[ignore]d everywhere: {len(both)}")
        print(
            f"gated with no platform assumption in the body: {len(free)} in "
            f"{len({r['file'] for r in free})} files"
        )
        print("would compile on:")
        for platform in PLATFORMS:
            n = sum(1 for r in gated if platform in r["runs_on"])
            print(f"  {platform:<11} {n} of {len(gated)}")
        print("files with gated tests and no test that runs on the platform:")
        for platform in ("windows", "macos", "linux"):
            print(f"  {platform:<11} {len(blind[platform])}")
        print("top crates by gated tests:")
        for crate, n in sorted(by_crate.items(), key=lambda kv: (-kv[1], kv[0]))[:12]:
            print(f"  {n:>4}  {crate}")
    if args.list_assumption_free:
        for r in free:
            print(
                f"{r['crate']}\t{r['file']}:{r['line']}\t{r['function']}\t"
                f"{runs_on_label(r['runs_on'])}"
            )
    if args.table:
        print(render_table(ledger))

    for problem in problems:
        print(f"FAIL: {problem}", file=sys.stderr)
    if problems:
        print(f"{len(problems)} problem(s)", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
